2023/12/03 06:57:04 [error] 69#69: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "localhost"
2023/12/03 06:57:04 [error] 69#69: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "localhost", referrer: "http://localhost/"
2023/12/03 06:57:07 [error] 71#71: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "localhost"
2023/12/03 06:57:07 [error] 71#71: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "localhost", referrer: "http://localhost/"
2023/12/03 06:57:14 [error] 75#75: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "localhost"
2023/12/03 06:57:14 [error] 75#75: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.65.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "localhost", referrer: "http://localhost/"
